spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.LongSerializer
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  config:
    import: file:./src/main/resources/config/secret.yml

server:
  port: 8080

assignment:
  dir: /Users/twan/Desktop/project-oj/upload/
